name: build-app

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.4

      - name: Run checkstyle
        working-directory: ./app
        run: make lint

  test:
    needs: [ build ]
    steps:
      - name: Run tests
        run: make test

  coverage:
    needs: [ test ]
    steps:
      - name: Run test coverage
        working-directory: ./app
        run: make report

      - name: Set jacoco.xml path for code climate
        run: JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco

      # upload coverage on code climate
      - name: Upload code climate report
        run: ./cc-test-reporter upload-coverage -r ${{ secrets.TEST_COVERAGE_ID }}
