name: build-app

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
        working-directory: ../

      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.4

      - name: Run checkstyle
        run: make lint

      - name: Run tests
        run: make test

      - name: Run test coverage
        run: make report

      - name: Download Code Climate test-reporter
        run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter

      - name: Make executable
        run: chmod +x ./cc-test-reporter

      - name: Set jacoco.xml path for code climate
        run: JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco

      - name: Upload code climate report
        run: ./cc-test-reporter upload-coverage -r ${{ secrets.TEST_COVERAGE_ID }}
