name: build-app

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4

      - name: Run checkstyle
        working-directory: ./app
        run: make lint

  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        working-directory: ./app
        run: make test

      - name: Run test coverage
        working-directory: ./app
        run: make report


  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_COVERAGE_ID }}
        with:
          coverageCommand: yarn coverage